### ISSUE TITLE
Handling Public Assignments

### ISSUE THREAD

**Issue by pblan** [paddel-xyz/matse-zettel#13]
## Proposal

Tag in e. g. `example-module.md`:
```yaml
---
type: module
# ...
semester: 2023-winter
---

# ...
```

Semester then refers to `2023-winter.md`:
```yaml
---
start: 2023-09-01
end: 2024-02-29
---

# ...
```

## Possible Uses

Assignments could be restricted based on the course's `semester` and the task's `date`:

```yaml
---
title: Stochastik 1
semester: 2023-winter
lecturers:
  - Prof. Dr. rer. nat. Daniel Gaigall
---

# ...
```

```yaml
---
date: 2023-10-08 
authors:
  - tmwnd
public: true # [true, false]
  restrict: semester # [semester, password, ...]
---

# ...
```
